version: "3.7"

services:
  proxy:
    image: nginx:latest
    depends_on: 
      - app
    volumes:
      - ${PWD}/conf/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "8080:80"
    expose: 
      - '80'
  app:
    build: .
    environment:
      verbose: 'true'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # volumes: 
    #   - webhook:/go
    working_dir: /go
    # container_name: webhook
    # ports:
    #   - "8080:8080"
    depends_on: 
      - db
    entrypoint: /go/webhook 2>/go/error.log
    expose: 
      - '8080'
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # ports:
      # <Port exposed> : < MySQL Port running inside container>
      # - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db_data:/var/lib/mysql
volumes:
    db_data: {}
    # webhook: {}
      
