version: "3.7"

services:
  proxy:
    image: mihaibalica/mynginx:1.0.1
    depends_on: 
      - app
    ports: 
      - "8080:80"
    expose: 
      - '80'
  app:
    image: mihaibalica/webhook:1.0.5
    environment:
      verbose: 'true'
      MYSQL_DATABASE: 'webhook'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'axiamed'
      # You can use whatever password you like
      MYSQL_PASSWORD: '~Pb%v(c)tTes@*&'
    # volumes: 
    #   - webhook:/go
    working_dir: /go
    # container_name: webhook
    # ports:
    #   - "8080:8080"
    depends_on: 
      - db
    entrypoint: /go/webhook 2>/go/error.log
    expose: 
      - '8080'
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'webhook'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'axiamed'
      # You can use whatever password you like
      MYSQL_PASSWORD: '~Pb%v(c)tTes@*&'
      MYSQL_ROOT_PASSWORD: 'Q!w@E#r$T%z/.+,p'
    # ports:
      # <Port exposed> : < MySQL Port running inside container>
      # - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db_data:/var/lib/mysql
volumes:
    db_data: {}
    # webhook: {}
      
